import { useState } from "react";
import type { Card } from "@/types/card";

const GAMES = [
  { value: "pokemon", label: "Pokémon" },
    { value: "magic", label: "Magic: The Gathering" },
      { value: "yugioh", label: "Yu-Gi-Oh!" },
        { value: "one_piece", label: "One Piece" },
          { value: "other", label: "Other" },
          ];

          const RARITIES = [
            { value: "common", label: "Common" },
              { value: "uncommon", label: "Uncommon" },
                { value: "rare", label: "Rare" },
                  { value: "ultra_rare", label: "Ultra Rare" },
                    { value: "secret_rare", label: "Secret Rare" },
                    ];

                    const CONDITIONS = [
                      { value: "mint", label: "Mint" },
                        { value: "near_mint", label: "Near Mint" },
                          { value: "excellent", label: "Excellent" },
                            { value: "good", label: "Good" },
                              { value: "played", label: "Played" },
                                { value: "poor", label: "Poor" },
                                ];

                                interface CardFormProps {
                                  initialData?: Partial<Card>;
                                    onSubmit: (data: Partial<Card>) => Promise<void>;
                                      loading?: boolean;
                                      }

                                      export function CardForm({ initialData, onSubmit, loading }: CardFormProps) {
                                        const [form, setForm] = useState<Partial<Card>>({
                                            name: initialData?.name || "",
                                                game: initialData?.game || "pokemon",
                                                    set_name: initialData?.set_name || "",
                                                        card_number: initialData?.card_number || "",
                                                            rarity: initialData?.rarity || "common",
                                                                condition: initialData?.condition || "near_mint",
                                                                    language: initialData?.language || "en",
                                                                        is_foil: initialData?.is_foil || false,
                                                                            is_first_edition: initialData?.is_first_edition || false,
                                                                                quantity: initialData?.quantity || 1,
                                                                                    purchase_price: initialData?.purchase_price || 0,
                                                                                        current_value: initialData?.current_value || 0,
                                                                                            image_url: initialData?.image_url || "",
                                                                                                notes: initialData?.notes || "",
                                                                                                  });

                                                                                                    const handleChange = (
                                                                                                        e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>
                                                                                                          ) => {
                                                                                                              const { name, value, type } = e.target;
                                                                                                                  const checked = (e.target as HTMLInputElement).checked;
                                                                                                                      setForm((prev) => ({
                                                                                                                            ...prev,
                                                                                                                                  [name]: type === "checkbox" ? checked : type === "number" ? Number(value) : value,
                                                                                                                                      }));
                                                                                                                                        };

                                                                                                                                          const handleSubmit = async (e: React.FormEvent) => {
                                                                                                                                              e.preventDefault();
                                                                                                                                                  await onSubmit(form);
                                                                                                                                                    };

                                                                                                                                                      return (
                                                                                                                                                          <form onSubmit={handleSubmit} className="space-y-4 max-w-2xl">
                                                                                                                                                                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                                                                                                                                                        <div>
                                                                                                                                                                                  <label className="block text-sm font-medium mb-1">Name *</label>
                                                                                                                                                                                            <input name="name" value={form.name} onChange={handleChange} required
                                                                                                                                                                                                        className="w-full rounded-lg border border-border bg-card p-2" />
                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                  <label className="block text-sm font-medium mb-1">Game</label>
                                                                                                                                                                                                                                            <select name="game" value={form.game} onChange={handleChange}
                                                                                                                                                                                                                                                        className="w-full rounded-lg border border-border bg-card p-2">
                                                                                                                                                                                                                                                                    {GAMES.map((g) => <option key={g.value} value={g.value}>{g.label}</option>)}
                                                                                                                                                                                                                                                                              </select>
                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                        <label className="block text-sm font-medium mb-1">Set</label>
                                                                                                                                                                                                                                                                                                                  <input name="set_name" value={form.set_name} onChange={handleChange}
                                                                                                                                                                                                                                                                                                                              className="w-full rounded-lg border border-border bg-card p-2" />
                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                        <label className="block text-sm font-medium mb-1">Card Number</label>
                                                                                                                                                                                                                                                                                                                                                                  <input name="card_number" value={form.card_number} onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                              className="w-full rounded-lg border border-border bg-card p-2" />
                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                        <label className="block text-sm font-medium mb-1">Rarity</label>
                                                                                                                                                                                                                                                                                                                                                                                                                  <select name="rarity" value={form.rarity} onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                              className="w-full rounded-lg border border-border bg-card p-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                          {RARITIES.map((r) => <option key={r.value} value={r.value}>{r.label}</option>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <label className="block text-sm font-medium mb-1">Condition</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <select name="condition" value={form.condition} onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full rounded-lg border border-border bg-card p-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {CONDITIONS.map((c) => <option key={c.value} value={c.value}>{c.label}</option>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label className="block text-sm font-medium mb-1">Language</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input name="language" value={form.language} onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="w-full rounded-lg border border-border bg-card p-2" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label className="block text-sm font-medium mb-1">Quantity</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input name="quantity" type="number" min="1" value={form.quantity} onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="w-full rounded-lg border border-border bg-card p-2" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label className="block text-sm font-medium mb-1">Purchase Price</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input name="purchase_price" type="number" step="0.01" value={form.purchase_price}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={handleChange} className="w-full rounded-lg border border-border bg-card p-2" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label className="block text-sm font-medium mb-1">Current Value</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input name="current_value" type="number" step="0.01" value={form.current_value}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={handleChange} className="w-full rounded-lg border border-border bg-card p-2" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex items-center gap-4 pt-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input name="is_foil" type="checkbox" checked={form.is_foil} onChange={handleChange} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Foil
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input name="is_first_edition" type="checkbox" checked={form.is_first_edition}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={handleChange} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1st Edition
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label className="block text-sm font-medium mb-1">Image URL</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input name="image_url" type="url" value={form.image_url} onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="w-full rounded-lg border border-border bg-card p-2" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <label className="block text-sm font-medium mb-1">Notes</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <textarea name="notes" value={form.notes} onChange={handleChange} rows={3}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full rounded-lg border border-border bg-card p-2" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button type="submit" disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="px-6 py-2 bg-primary text-primary-foreground rounded-lg hover:opacity-90 disabled:opacity-50">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {loading ? "Saving..." : initialData?.name ? "Update Card" : "Add Card"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            