import { useState, useEffect } from "react";
import { Plus, Pencil, Trash2, Globe, Lock } from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import {
  getCollections, createCollection, updateCollection, deleteCollection,
    type Collection,
    } from "@/lib/collections";

    export default function CollectionsPage() {
      const { user } = useAuth();
        const [collections, setCollections] = useState<Collection[]>([]);
          const [loading, setLoading] = useState(true);
            const [showForm, setShowForm] = useState(false);
              const [editingId, setEditingId] = useState<string | null>(null);
                const [name, setName] = useState("");
                  const [description, setDescription] = useState("");
                    const [isPublic, setIsPublic] = useState(false);

                      const fetchCollections = async () => {
                          if (!user) return;
                              try {
                                    const data = await getCollections(user.id);
                                          setCollections(data);
                                              } catch (err) {
                                                    console.error(err);
                                                        } finally {
                                                              setLoading(false);
                                                                  }
                                                                    };

                                                                      useEffect(() => { fetchCollections(); }, [user]);

                                                                        const resetForm = () => {
                                                                            setName(""); setDescription(""); setIsPublic(false);
                                                                                setShowForm(false); setEditingId(null);
                                                                                  };

                                                                                    const handleSubmit = async (e: React.FormEvent) => {
                                                                                        e.preventDefault();
                                                                                            if (!user) return;
                                                                                                try {
                                                                                                      if (editingId) {
                                                                                                              const updated = await updateCollection(editingId, { name, description, is_public: isPublic });
                                                                                                                      setCollections((prev) => prev.map((c) => (c.id === editingId ? updated : c)));
                                                                                                                            } else {
                                                                                                                                    const created = await createCollection({ user_id: user.id, name, description, is_public: isPublic });
                                                                                                                                            setCollections((prev) => [created, ...prev]);
                                                                                                                                                  }
                                                                                                                                                        resetForm();
                                                                                                                                                            } catch (err) {
                                                                                                                                                                  console.error(err);
                                                                                                                                                                      }
                                                                                                                                                                        };

                                                                                                                                                                          const handleEdit = (c: Collection) => {
                                                                                                                                                                              setEditingId(c.id); setName(c.name);
                                                                                                                                                                                  setDescription(c.description || ""); setIsPublic(c.is_public);
                                                                                                                                                                                      setShowForm(true);
                                                                                                                                                                                        };

                                                                                                                                                                                          const handleDelete = async (id: string) => {
                                                                                                                                                                                              if (!confirm("Delete this collection?")) return;
                                                                                                                                                                                                  try {
                                                                                                                                                                                                        await deleteCollection(id);
                                                                                                                                                                                                              setCollections((prev) => prev.filter((c) => c.id !== id));
                                                                                                                                                                                                                  } catch (err) {
                                                                                                                                                                                                                        console.error(err);
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                    <div className="space-y-6">
                                                                                                                                                                                                                                          <div className="flex items-center justify-between">
                                                                                                                                                                                                                                                  <h1 className="text-2xl font-bold">My Collections</h1>
                                                                                                                                                                                                                                                          <button onClick={() => { resetForm(); setShowForm(true); }}
                                                                                                                                                                                                                                                                    className="flex items-center gap-2 px-4 py-2 bg-primary text-primary-foreground rounded-lg hover:opacity-90">
                                                                                                                                                                                                                                                                              <Plus className="w-4 h-4" /> New Collection
                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                  {showForm && (
                                                                                                                                                                                                                                                                                                          <form onSubmit={handleSubmit} className="p-4 rounded-xl border border-border bg-card space-y-3">
                                                                                                                                                                                                                                                                                                                    <input type="text" placeholder="Collection name" required
                                                                                                                                                                                                                                                                                                                                value={name} onChange={(e) => setName(e.target.value)}
                                                                                                                                                                                                                                                                                                                                            className="w-full px-3 py-2 rounded-lg border border-border bg-background" />
                                                                                                                                                                                                                                                                                                                                                      <textarea placeholder="Description (optional)" rows={2}
                                                                                                                                                                                                                                                                                                                                                                  value={description} onChange={(e) => setDescription(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                              className="w-full px-3 py-2 rounded-lg border border-border bg-background" />
                                                                                                                                                                                                                                                                                                                                                                                        <label className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                    <input type="checkbox" checked={isPublic} onChange={(e) => setIsPublic(e.target.checked)} />
                                                                                                                                                                                                                                                                                                                                                                                                                <span className="text-sm">Public collection</span>
                                                                                                                                                                                                                                                                                                                                                                                                                          </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                <button type="submit" className="px-4 py-2 bg-primary text-primary-foreground rounded-lg">
                                                                                                                                                                                                                                                                                                                                                                                                                                                              {editingId ? "Update" : "Create"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button type="button" onClick={resetForm} className="px-4 py-2 border border-border rounded-lg">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Cancel
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {loading ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex justify-center py-12">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="animate-spin rounded-full h-8 w-8 border-2 border-primary border-t-transparent" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ) : collections.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="text-center py-12 text-muted-foreground">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p>No collections yet. Create your first one!</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {collections.map((c) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div key={c.id} className="rounded-xl border border-border bg-card p-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex items-start justify-between mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 className="font-semibold">{c.name}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {c.is_public ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Globe className="w-4 h-4 text-green-500" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Lock className="w-4 h-4 text-muted-foreground" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {c.description && <p className="text-sm text-muted-foreground mb-3">{c.description}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex gap-2 pt-2 border-t border-border">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button onClick={() => handleEdit(c)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Pencil className="w-3.5 h-3.5" /> Edit
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button onClick={() => handleDelete(c.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="flex items-center gap-1 text-sm text-red-500 hover:text-red-700 ml-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Trash2 className="w-3.5 h-3.5" /> Delete
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }