import { useState } from "react";
import { Search } from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { searchCards, getCardsByGame } from "@/lib/cards";
import { CardItem } from "@/components/cards/CardItem";
import { deleteCard } from "@/lib/cards";
import type { Card } from "@/types/card";

const GAMES = [
  { value: "", label: "All Games" },
    { value: "pokemon", label: "Pokemon" },
      { value: "magic", label: "MTG" },
        { value: "yugioh", label: "Yu-Gi-Oh!" },
          { value: "one_piece", label: "One Piece" },
            { value: "other", label: "Other" },
            ];

            const RARITIES = ["", "common", "uncommon", "rare", "ultra_rare", "secret_rare", "promo"];
            const CONDITIONS = ["", "mint", "near_mint", "excellent", "good", "light_played", "played", "poor"];

            export default function SearchPage() {
              const { user } = useAuth();
                const [query, setQuery] = useState("");
                  const [gameFilter, setGameFilter] = useState("");
                    const [rarityFilter, setRarityFilter] = useState("");
                      const [conditionFilter, setConditionFilter] = useState("");
                        const [results, setResults] = useState<Card[]>([]);
                          const [loading, setLoading] = useState(false);
                            const [searched, setSearched] = useState(false);

                              const handleSearch = async (e: React.FormEvent) => {
                                  e.preventDefault();
                                      if (!user) return;
                                          setLoading(true);
                                              setSearched(true);
                                                  try {
                                                        let data: Card[];
                                                              if (gameFilter) {
                                                                      data = await getCardsByGame(user.id, gameFilter);
                                                                            } else {
                                                                                    data = await searchCards(user.id, query);
                                                                                          }
                                                                                                if (rarityFilter) data = data.filter((c) => c.rarity === rarityFilter);
                                                                                                      if (conditionFilter) data = data.filter((c) => c.condition === conditionFilter);
                                                                                                            if (query && gameFilter) data = data.filter((c) => c.name.toLowerCase().includes(query.toLowerCase()));
                                                                                                                  setResults(data);
                                                                                                                      } catch (err) {
                                                                                                                            console.error(err);
                                                                                                                                } finally {
                                                                                                                                      setLoading(false);
                                                                                                                                          }
                                                                                                                                            };

                                                                                                                                              const handleDelete = async (id: string) => {
                                                                                                                                                  if (!confirm("Delete this card?")) return;
                                                                                                                                                      try {
                                                                                                                                                            await deleteCard(id);
                                                                                                                                                                  setResults((prev) => prev.filter((c) => c.id !== id));
                                                                                                                                                                      } catch (err) {
                                                                                                                                                                            console.error(err);
                                                                                                                                                                                }
                                                                                                                                                                                  };

                                                                                                                                                                                    return (
                                                                                                                                                                                        <div className="space-y-6">
                                                                                                                                                                                              <h1 className="text-2xl font-bold">Advanced Search</h1>
                                                                                                                                                                                                    <form onSubmit={handleSearch} className="space-y-3">
                                                                                                                                                                                                            <div className="relative">
                                                                                                                                                                                                                      <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                                                                                                                                                                                                                                <input type="text" placeholder="Search by card name..."
                                                                                                                                                                                                                                            value={query} onChange={(e) => setQuery(e.target.value)}
                                                                                                                                                                                                                                                        className="w-full pl-10 pr-4 py-2 rounded-lg border border-border bg-card" />
                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                        <div className="flex flex-wrap gap-3">
                                                                                                                                                                                                                                                                                  <select value={gameFilter} onChange={(e) => setGameFilter(e.target.value)}
                                                                                                                                                                                                                                                                                              className="px-3 py-2 rounded-lg border border-border bg-card text-sm">
                                                                                                                                                                                                                                                                                                          {GAMES.map((g) => <option key={g.value} value={g.value}>{g.label}</option>)}
                                                                                                                                                                                                                                                                                                                    </select>
                                                                                                                                                                                                                                                                                                                              <select value={rarityFilter} onChange={(e) => setRarityFilter(e.target.value)}
                                                                                                                                                                                                                                                                                                                                          className="px-3 py-2 rounded-lg border border-border bg-card text-sm">
                                                                                                                                                                                                                                                                                                                                                      <option value="">All Rarities</option>
                                                                                                                                                                                                                                                                                                                                                                  {RARITIES.filter(Boolean).map((r) => (
                                                                                                                                                                                                                                                                                                                                                                                <option key={r} value={r}>{r.replace(/_/g, " ")}</option>
                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                      </select>
                                                                                                                                                                                                                                                                                                                                                                                                                <select value={conditionFilter} onChange={(e) => setConditionFilter(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                            className="px-3 py-2 rounded-lg border border-border bg-card text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                        <option value="">All Conditions</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    {CONDITIONS.filter(Boolean).map((c) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <option key={c} value={c}>{c.replace(/_/g, " ")}</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="px-4 py-2 bg-primary text-primary-foreground rounded-lg hover:opacity-90">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Search
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {loading ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex justify-center py-12">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="animate-spin rounded-full h-8 w-8 border-2 border-primary border-t-transparent" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ) : searched && results.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-center py-8 text-muted-foreground">No cards found.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {results.map((card) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <CardItem key={card.id} card={card} onDelete={handleDelete} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }