import { useState, useEffect } from "react";
import { Save } from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { supabase } from "@/lib/supabase";

const GAMES = [
  { value: "", label: "None" },
    { value: "pokemon", label: "Pokemon" },
      { value: "magic", label: "Magic: The Gathering" },
        { value: "yugioh", label: "Yu-Gi-Oh!" },
          { value: "one_piece", label: "One Piece" },
            { value: "other", label: "Other" },
            ];

            export default function SettingsPage() {
              const { user } = useAuth();
                const [displayName, setDisplayName] = useState("");
                  const [bio, setBio] = useState("");
                    const [favoriteGame, setFavoriteGame] = useState("");
                      const [loading, setLoading] = useState(false);
                        const [saved, setSaved] = useState(false);

                          useEffect(() => {
                              if (!user) return;
                                  supabase
                                        .from("profiles")
                                              .select("*")
                                                    .eq("id", user.id)
                                                          .single()
                                                                .then(({ data }: { data: any }) => {
                                                                        if (data) {
                                                                                  setDisplayName(data.display_name || "");
                                                                                            setBio(data.bio || "");
                                                                                                      setFavoriteGame(data.favorite_game || "");
                                                                                                              }
                                                                                                                    });
                                                                                                                      }, [user]);

                                                                                                                        const handleSave = async (e: React.FormEvent) => {
                                                                                                                            e.preventDefault();
                                                                                                                                if (!user) return;
                                                                                                                                    setLoading(true);
                                                                                                                                        setSaved(false);
                                                                                                                                            try {
                                                                                                                                                  await supabase
                                                                                                                                                          .from("profiles")
                                                                                                                                                                  .update({
                                                                                                                                                                            display_name: displayName || null,
                                                                                                                                                                                      bio: bio || null,
                                                                                                                                                                                                favorite_game: favoriteGame || null,
                                                                                                                                                                                                        })
                                                                                                                                                                                                                .eq("id", user.id);
                                                                                                                                                                                                                      setSaved(true);
                                                                                                                                                                                                                            setTimeout(() => setSaved(false), 3000);
                                                                                                                                                                                                                                } catch (err) {
                                                                                                                                                                                                                                      console.error(err);
                                                                                                                                                                                                                                          } finally {
                                                                                                                                                                                                                                                setLoading(false);
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                            <div className="space-y-6 max-w-xl">
                                                                                                                                                                                                                                                                  <h1 className="text-2xl font-bold">Settings</h1>
                                                                                                                                                                                                                                                                        <form onSubmit={handleSave} className="space-y-4">
                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                          <label className="block text-sm font-medium mb-1">Email</label>
                                                                                                                                                                                                                                                                                                    <input type="email" disabled value={user?.email || ""}
                                                                                                                                                                                                                                                                                                                className="w-full px-3 py-2 rounded-lg border border-border bg-secondary text-muted-foreground" />
                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                          <label className="block text-sm font-medium mb-1">Display Name</label>
                                                                                                                                                                                                                                                                                                                                                    <input type="text" value={displayName}
                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => setDisplayName(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                            className="w-full px-3 py-2 rounded-lg border border-border bg-card" />
                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                      <label className="block text-sm font-medium mb-1">Bio</label>
                                                                                                                                                                                                                                                                                                                                                                                                                <textarea rows={3} value={bio}
                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={(e) => setBio(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                        className="w-full px-3 py-2 rounded-lg border border-border bg-card" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <label className="block text-sm font-medium mb-1">Favorite Game</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <select value={favoriteGame}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setFavoriteGame(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full px-3 py-2 rounded-lg border border-border bg-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {GAMES.map((g) => <option key={g.value} value={g.value}>{g.label}</option>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button type="submit" disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="flex items-center gap-2 px-4 py-2 bg-primary text-primary-foreground rounded-lg hover:opacity-90 disabled:opacity-50">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Save className="w-4 h-4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {loading ? "Saving..." : "Save Changes"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {saved && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-sm text-green-600">Settings saved successfully!</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }